LANGUAGES = {
    "fr": {
        "welcome": "Bienvenue, {username} !",
        "db_selected": "Base de données sélectionnée : {db}",
        "record_inserted": "Enregistrement inséré",
        "permission_denied": "Permission refusée. Vous n'avez pas les droits nécessaires.",
        "table_not_found": "Table non trouvée",
        "command_not_supported": "Commande non prise en charge. Veuillez vérifier la syntaxe.",
        "command_title": "Entrez la commande",
        "error": "Erreur : {error}",
        "user_created": "Utilisateur {username} créé",
        "user_altered": "Utilisateur {username} modifié",
        "user_dropped": "Utilisateur {username} supprimé",
        "db_exists": "Base de données existe déjà",
        "db_created": "Base de données {db} créée",
        "db_dropped": "Base de données {db} supprimée",
        "table_created": "Table {table} créée",
        "table_dropped": "Table {table} supprimée",
        "table_exists": "Table existe déjà",
        "invalid_type": "Type invalide pour {col} : attendu {type}",
        "unique_constraint": "La valeur {val} pour {col} doit être unique",
        "invalid_columns": "Colonnes invalides",
        "no_row_updated": "Aucune ligne modifiée",
        "column_already_exists": "La colonne existe déjà",
        "column_not_exists": "La colonne n'existe pas",
        "data_updated": "Données mises à jour",
        "table_truncated": "Table {table} vidée",
        "table_structure": "Structure de {table} :\n{structure}",
        "backup_created": "Sauvegarde effectuée : {backup_file}",
        "restore_completed": "Restauration effectuée depuis : {backup_file}",
        "index_created": "Index {index_type} créé sur {table}.{column}",
        "otp_sent": "Un code OTP a été envoyé. Veuillez le saisir : ",
        "otp_invalid": "Code OTP invalide. Authentification échouée.",
    "session_started": "Session démarrée.",
        "list_databases": "Bases de données :\n{list}",
        "list_tables": "Tables :\n{list}",
        "replication_error": "Erreur de réplication vers {node} : {error}",
        "admin_created": "Admin créé avec succès.",
        "auth_failed": "Échec de l'authentification",
        "training_file_not_found": "Fichier de données d'entraînement non trouvé.",
        "training_in_progress": "Entraînement en cours...",
        "model_trained": "Modèle entraîné et sauvegardé sous {model}",
        "exit": "Fermeture du système de base de données. Au revoir !",
        "ssl_files_notice": "Les fichiers SSL sont chargés depuis le répertoire de main.py.",
        "user_exists": "Utilisateur déjà existant",
        "user_not_found": "Utilisateur non trouvé",
        "column_invalid": "Colonne invalide",
        "db_not_found": "Base de données non trouvée",
        "no_db_selected": "Aucune base de données sélectionnée",
        "nlp_model_not_trained": "Modèle NLP non entraîné",
        "translated_query": "Requête traduite : {sql_query}",
        "none": "Aucune",
        "user": "Utilisateur",
        "db": "Base de données",
        "not_null_violation": "La colonne {col} ne peut pas être NULL.",
        "default_used": "Valeur par défaut utilisée pour {col}: {value}.",
        "unique_violation": "La valeur {val} pour {col} doit être unique.",
        "primary_key_duplicate": "Duplication de clé primaire pour {col}: {val}.",
        "foreign_key_violation": "Violation de clé étrangère pour {col}: {val} (référence {ref_table}.{ref_col}).",
        "check_violation": "Violation de contrainte CHECK pour {col}: {condition}.",
        "table_sharded": "Table {table} partitionnée en {num_shards} shards sur la colonne {shard_column}.",
        "materialized_view_created": "Vue matérialisée {view_name} créée.",
        "materialized_view_refreshed": "Vue matérialisée {view_name} actualisée.",
        "cte_created": "CTE {cte_name} créé.",
        "savepoint_created": "Savepoint {savepoint_name} créé.",
        "savepoint_rolled_back": "Revenu au savepoint {savepoint_name}.",
        "savepoint_released": "Savepoint {savepoint_name} libéré.",
        "all_privileges_granted": "Tous les privilèges accordés à {username}.",
        "all_privileges_revoked": "Tous les privilèges révoqués pour {username}.",
        "merge_completed": "Opération MERGE terminée sur {table}.",
        "nested_transaction_started": "Transaction imbriquée démarrée.",
        "nested_transaction_committed": "Transaction imbriquée validée.",
        "nested_transaction_rolled_back": "Transaction imbriquée annulée.",
        "json_extraction_error": "Erreur d'extraction JSON : {error}",
        "array_aggregation": "Agrégation de tableau terminée.",
        "full_outer_join_completed": "Jointure FULL OUTER terminée entre {table1} et {table2}.",
        "division_completed": "Opération de division terminée entre {table1} et {table2}.",
        "json_table_error": "Erreur lors de l'extraction JSON_TABLE : {error}",
        "generated_column_added": "Colonne générée {column} ajoutée à {table}.",
        "recursive_cte_completed": "CTE récursif {cte_name} exécuté avec succès.",
        "sequence_created": "Séquence {sequence} créée.",
        "sequence_exists": "La séquence {sequence} existe déjà.",
        "enum_created": "Type ENUM {enum} créé.",
        "enum_exists": "Le type ENUM {enum} existe déjà.",
        "fdw_created": "Foreign Data Wrapper {fdw} créé.",
        "fdw_exists": "Le Foreign Data Wrapper {fdw} existe déjà.",
        "tablespace_created": "Tablespace {tablespace} créé.",
        "tablespace_exists": "Le tablespace {tablespace} existe déjà.",
        "location_not_found": "Emplacement {location} introuvable.",
        "no_history_found": "Aucun historique trouvé pour la table {table}.",
        "data_masking_added": "Masquage des données ajouté à la colonne {column} dans la table {table}.",
        "row_level_security_enabled": "Sécurité au niveau des lignes activée pour la table {table}.",
        "query_hint_applied": "Indice de requête appliqué : {hint}.",
        "backup_not_found": "Fichier de sauvegarde introuvable : {backup_file}",
        "query_failed": "La requête a échoué : {error}",
        "query_no_results": "Aucun résultat trouvé.",
        "query_results": "Résultats : {results}",
        "language_changed": "Langue changée à {language}",
        "language_not_supported": "Langue non supportée",
        "db_creation_failed": "Erreur : La création de la base de données a échoué. {error}",
        "user_creation_failed": "Erreur : La création de l'utilisateur a échoué. {error}",
        "insert_failed": "Erreur : L'insertion a échoué. {error}",
        "db_deletion_failed": "Erreur : La suppression de la base de données a échoué. {error}",
        "admin_password": "Mot de passe administrateur : ",
        "critical_error": "Erreur critique : {error}",
        "initialization_failed": "Échec de l'initialisation : {error}",
        "create_admin_password": "Veuillez créer un mot de passe administrateur :",
        "decryption_failed": "Échec du déchiffrement : {error}",
        "procedure_created": "Procédure {name} enregistrée.",
        "procedure_executed": "Procédure {name} exécutée. Résultat: {result}",
        "procedure_not_found": "Procédure {name} non trouvée.",
        "procedure_error": "Erreur d'exécution de la procédure {name}: {error}",
        "prompt": "Entrez votre requête SQL ou commande :"
    },
    "en": {
        "welcome": "Welcome, {username}!",
        "db_selected": "Database selected: {db}",
        "record_inserted": "Record inserted",
        "permission_denied": "Permission denied",
        "table_not_found": "Table not found",
        "command_not_supported": "Command not supported. Please check the syntax.",
        "command_title": "Enter command",
        "error": "Error: {error}",
        "user_created": "User {username} created",
        "user_altered": "User {username} altered",
        "user_dropped": "User {username} dropped",
        "db_exists": "Database already exists",
        "db_created": "Database {db} created",
        "db_dropped": "Database {db} dropped",
        "table_created": "Table {table} created",
        "table_dropped": "Table {table} dropped",
        "table_exists": "Table already exists",
        "invalid_type": "Invalid type for {col}: expected {type}",
        "unique_constraint": "Value {val} for {col} must be unique",
        "invalid_columns": "Invalid columns",
        "no_row_updated": "No rows updated",
        "column_already_exists": "Column already exists",
        "column_not_exists": "Column does not exist",
        "data_updated": "Data updated",
        "table_truncated": "Table {table} truncated",
        "table_structure": "Structure of {table}:\n{structure}",
        "backup_created": "Backup created: {backup_file}",
        "restore_completed": "Restored from backup: {backup_file}",
        "index_created": "{index_type} index created on {table}.{column}",
        "otp_sent": "An OTP code has been sent. Please enter it: ",
        "otp_invalid": "Invalid OTP code. Authentication failed.",
    "session_started": "Session started.",
        "list_databases": "Databases:\n{list}",
        "list_tables": "Tables:\n{list}",
        "replication_error": "Replication error to {node}: {error}",
        "admin_created": "Admin created successfully.",
        "auth_failed": "Authentication failed",
        "training_file_not_found": "Training data file not found.",
        "training_in_progress": "Training in progress...",
        "model_trained": "Model trained and saved as {model}",
        "exit": "Exiting the database system. Goodbye!",
        "ssl_files_notice": "SSL files are loaded from the same directory as main.py.",
        "user_exists": "User already exists",
        "user_not_found": "User not found",
        "column_invalid": "Invalid column",
        "db_not_found": "Database not found",
        "no_db_selected": "No database selected",
        "nlp_model_not_trained": "NLP model not trained",
        "translated_query": "Translated query: {sql_query}",
        "none": "None",
        "user": "User",
        "db": "Database",
        "not_null_violation": "Column {col} cannot be NULL.",
        "default_used": "Default value used for {col}: {value}.",
        "unique_violation": "Value {val} for {col} must be unique.",
        "primary_key_duplicate": "Primary key duplication for {col}: {val}.",
        "foreign_key_violation": "Foreign key violation for {col}: {val} (reference {ref_table}.{ref_col}).",
        "check_violation": "CHECK constraint violation for {col}: {condition}.",
        "table_sharded": "Table {table} sharded into {num_shards} shards on column {shard_column}.",
        "materialized_view_created": "Materialized view {view_name} created.",
        "materialized_view_refreshed": "Materialized view {view_name} refreshed.",
        "cte_created": "CTE {cte_name} created.",
        "savepoint_created": "Savepoint {savepoint_name} created.",
        "savepoint_rolled_back": "Rolled back to savepoint {savepoint_name}.",
        "savepoint_released": "Savepoint {savepoint_name} released.",
        "all_privileges_granted": "All privileges granted to {username}.",
        "all_privileges_revoked": "All privileges revoked from {username}.",
        "merge_completed": "MERGE operation completed on {table}.",
        "nested_transaction_started": "Nested transaction started.",
        "nested_transaction_committed": "Nested transaction committed.",
        "nested_transaction_rolled_back": "Nested transaction rolled back.",
        "json_extraction_error": "JSON extraction error: {error}",
        "array_aggregation": "Array aggregation completed.",
        "full_outer_join_completed": "FULL OUTER JOIN completed between {table1} and {table2}.",
        "division_completed": "Division operation completed between {table1} and {table2}.",
        "json_table_error": "Error during JSON_TABLE extraction: {error}",
        "generated_column_added": "Generated column {column} added to {table}.",
        "recursive_cte_completed": "Recursive CTE {cte_name} executed successfully.",
        "sequence_created": "Sequence {sequence} created.",
        "sequence_exists": "Sequence {sequence} already exists.",
        "enum_created": "ENUM type {enum} created.",
        "enum_exists": "ENUM type {enum} already exists.",
        "fdw_created": "Foreign Data Wrapper {fdw} created.",
        "fdw_exists": "Foreign Data Wrapper {fdw} already exists.",
        "tablespace_created": "Tablespace {tablespace} created.",
        "tablespace_exists": "Tablespace {tablespace} already exists.",
        "location_not_found": "Location {location} not found.",
        "no_history_found": "No history found for table {table}.",
        "data_masking_added": "Data masking added to column {column} in table {table}.",
        "row_level_security_enabled": "Row-level security enabled for table {table}.",
        "query_hint_applied": "Query hint applied: {hint}.",
        "backup_not_found": "Backup file not found: {backup_file}",
        "query_failed": "Query failed: {error}",
        "query_no_results": "No results found.",
        "query_results": "Results: {results}",
        "language_changed": "Language changed to {language}",
        "language_not_supported": "Language not supported",
        "db_creation_failed": "Error: Database creation failed. {error}",
        "user_creation_failed": "Error: User creation failed. {error}",
        "insert_failed": "Error: Insert operation failed. {error}",
        "db_deletion_failed": "Error: Database deletion failed. {error}",
        "admin_password": "Administrator password: ",
        "critical_error": "Critical error: {error}",
        "initialization_failed": "Initialization failed: {error}",
        "create_admin_password": "Enter password for admin user: ",
        "decryption_failed": "Decryption failed: {error}",
        "procedure_created": "Procedure {name} saved.",
        "procedure_executed": "Procedure {name} executed. Result: {result}",
        "procedure_not_found": "Procedure {name} not found.",
        "procedure_error": "Error executing procedure {name}: {error}",
        "prompt": "Enter your SQL or command:"
    }
}